module VoidGui
  ASCII = {
    single_line: {
      up_down:         String.new(Bytes[179]),
      left_up_down:    String.new(Bytes[180]),
      left_down:       String.new(Bytes[191]),
      up_right:        String.new(Bytes[192]),
      left_up_right:   String.new(Bytes[193]),
      left_down_right: String.new(Bytes[194]),
      up_down_right:   String.new(Bytes[195]),
      left_right:      String.new(Bytes[196]),
      intersection:    String.new(Bytes[197]),
      up_left:         String.new(Bytes[217]),
      down_right:      String.new(Bytes[218]),
    },

    double_line: {
      up_down:         String.new(Bytes[186]),
      left_up_down:    String.new(Bytes[185]),
      left_down:       String.new(Bytes[187]),
      up_right:        String.new(Bytes[200]),
      left_up_right:   String.new(Bytes[202]),
      left_down_right: String.new(Bytes[203]),
      up_down_right:   String.new(Bytes[204]),
      left_right:      String.new(Bytes[205]),
      intersection:    String.new(Bytes[206]),
      up_left:         String.new(Bytes[188]),
      down_right:      String.new(Bytes[201]),
    },

    block: {
      full_char: String.new(Bytes[219]),
      lh_char:   String.new(Bytes[220]),
      uh_char:   String.new(Bytes[223]),
      square:    String.new(Bytes[254]),
    },

    dotted: {
      low:    String.new(Bytes[176]),
      medium: String.new(Bytes[177]),
      high:   String.new(Bytes[178]),
    },

    space: {
      normal: String.new(Bytes[32]),
      nbsp:   String.new(Bytes[255]),
    },

    special: {
      x:                  String.new(Bytes[158]),
      upper_slash_zero:   String.new(Bytes[157]),
      lower_slash_zero:   String.new(Bytes[155]),
      double_arrow_left:  String.new(Bytes[174]),
      double_arrow_right: String.new(Bytes[175]),
      small_o:            String.new(Bytes[167]),
      degree:             String.new(Bytes[248]),
      double_dot:         String.new(Bytes[249]),
      space_dot:          String.new(Bytes[250]),
      sub1:               String.new(Bytes[251]),
      sub2:               String.new(Bytes[252]),
      sub3:               String.new(Bytes[253]),
      threequals:         String.new(Bytes[240]),
      high_line:          String.new(Bytes[238]),
      vert_broken_bar:    String.new(Bytes[221]),
      double_underscore:  String.new(Bytes[242]),
    },
  }

  UNICODE = {
    box: {
      light_solid_horizontal:       '\u{2500}',
      heavy_solid_horizontal:       '\u{2501}',
      light_solid_vertical:         '\u{2502}',
      heavy_solid_vertical:         '\u{2503}',
      light_triple_dash_horizontal: '\u{2504}',
      heavy_triple_dash_horizontal: '\u{2505}',
      light_triple_dash_vertical:   '\u{2506}',
      heavy_triple_dash_vertical:   '\u{2507}',
      light_quad_dash_horizontal:   '\u{2508}',
      heavy_quad_dash_horizontal:   '\u{2509}',
      light_quad_dash_vertical:     '\u{250A}',
      heavy_quad_dash_vertical:     '\u{250B}',
      light_down_right:             '\u{250C}',
      down_light_right_heavy:       '\u{250D}',
      down_heavy_right_light:       '\u{250E}',
      heavy_down_right:             '\u{250F}',
      light_down_left:              '\u{2510}',
      down_light_left_heavy:        '\u{2511}',
      down_heavy_left_light:        '\u{2512}',
      heavy_down_left:              '\u{2513}',
      light_up_right:               '\u{2514}',
      up_light_right_heavy:         '\u{2515}',
      up_heavy_right_light:         '\u{2516}',
      heavy_up_right:               '\u{2517}',
      light_up_left:                '\u{2518}',
      up_light_left_heavy:          '\u{2519}',
      up_heavy_left_light:          '\u{251A}',
      heavy_up_left:                '\u{251B}',

      light_vertical_right:       '\u{251C}',
      vertical_light_right_heavy: '\u{251D}',
      up_heavy_right_down_light:  '\u{251E}',
      up_heavy_right_up_light:    '\u{251F}',
      vertical_heavy_right_light: '\u{2520}',
      down_light_right_up_heavy:  '\u{2521}',
      up_light_right_down_heavy:  '\u{2522}',
      heavy_vertical_right:       '\u{2523}',

      light_vertical_left:       '\u{2524}',
      vertical_light_left_heavy: '\u{2525}',
      up_heavy_left_down_light:  '\u{2526}',
      down_heavy_left_up_light:  '\u{2527}',
      vertical_heavy_left_light: '\u{2528}',
      down_light_left_up_heavy:  '\u{2529}',
      up_light_left_down_heavy:  '\u{252A}',
      heavy_vertical_left:       '\u{252B}',

      light_down_horizontal:       '\u{252C}',
      left_heavy_right_down_light: '\u{252D}',
      right_heavy_left_down_light: '\u{252E}',
      down_light_horizontal_heavy: '\u{252F}',
      down_heavy_horizontal_light: '\u{2530}',
      right_light_left_down_heavy: '\u{2531}',
      left_light_right_down_heavy: '\u{2532}',
      heavy_down_horizontal:       '\u{2533}',

      light_up_horizontal:             '\u{2534}',
      left_heavy_right_up_light:       '\u{2535}',
      right_heavy_left_up_light:       '\u{2536}',
      up_light_horizontal_heavy:       '\u{2537}',
      up_heavy_horizontal_light:       '\u{2538}',
      right_light_left_up_heavy:       '\u{2539}',
      left_light_right_up_heavy:       '\u{253A}',
      heavy_up_horizontal:             '\u{253B}',
      light_vertical_horizontal:       '\u{253C}',
      left_heavy_right_vertical_light: '\u{253D}',
      right_heavy_left_vertical_light: '\u{253E}',
      vertical_light_horizontal_heavy: '\u{253F}',
      up_heavy_down_horizontal_light:  '\u{2540}',
      down_heavy_up_horizontal_light:  '\u{2541}',
      vertical_heavy_horizontal_heavy: '\u{2542}',
      left_up_heavy_right_down_light:  '\u{2543}',
      right_up_heavy_left_down_light:  '\u{2544}',
      left_down_heavy_right_up_light:  '\u{2545}',
      right_down_heavy_left_up_light:  '\u{2546}',
      down_light_up_horizontal_heavy:  '\u{2547}',
      up_light_down_horizontal_heavy:  '\u{2548}',
      right_light_left_vertical_heavy: '\u{2549}',
      left_light_right_vertical_heavy: '\u{254A}',
      heavy_vertical_horizonal:        '\u{254B}',

    },

    block: {
      lower_eighth:         '\u{2581}',
      lower_quarter:        '\u{2582}',
      lower_three_eighths:  '\u{2583}',
      lower_half:           '\u{2584}',
      lower_five_eighths:   '\u{2585}',
      lower_three_quarters: '\u{2586}',
      lower_seven_eighths:  '\u{2587}',
      full:                 '\u{2588}',
    },

    shade: {
      light:  '\u{2591}',
      medium: '\u{2592}',
      heavy:  '\u{2593}',
    },

    x: {
      cross_over:   '\u{292B}',
      cross_under: '\u{292C}',

    },

    arrow: {
      right_rounded: '\u{279C}',
    }
  }
end
